name = "SEU-PROJETO-AQUI"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "ORDERS_KV"
id = "SEU_KV_NAMESPACE_ID"

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "SEU_R2_BUCKET"
